added to configuration, the sucess command to execute in pressed by ubiquity, and the first boot commands to execute for the PinguyBuilder first boot service

diff --git a/usr/bin/PinguyBuilder b/usr/bin/PinguyBuilder
--- a/usr/bin/PinguyBuilder
+++ b/usr/bin/PinguyBuilder
@@ -8,79 +8,6 @@ if [ "$(whoami)" != "root" ]; then
     exit 1
 fi
 
-#create PinguyBuilder-firstboot script if it doesn't exist and populate with at least removal of the ubiquity*.desktop file from users Desktop and fix for recovery mode
-fbtest=`grep "REM302" /etc/init.d/PinguyBuilder-firstboot`
-
-if [ "$fbtest" = "" ]; then
-    cat > /etc/init.d/PinguyBuilder-firstboot <<FOO
-#! /bin/sh
-### BEGIN INIT INFO
-# Provides:          PinguyBuilder-firstboot
-# Required-Start:    \$remote_fs \$syslog \$all
-# Required-Stop:
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: Run firstboot items for PinguyBuilder after a remastered system has been installed
-### END INIT INFO
-
-PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
-
-. /lib/init/vars.sh
-. /lib/lsb/init-functions
-
-do_start() {
-        #REM302
-        if [ "\`cat /proc/cmdline | grep casper\`" = "" ]; then
-            [ "\$VERBOSE" != no ] && log_begin_msg "Running PinguyBuilder-firstboot"
-            (sleep 60 && update-rc.d -f PinguyBuilder-firstboot remove) &
-            sed -i -e 's/root:x:/root:!:/g' /etc/shadow
-            rm -rf /home/*/*/ubiquity*.desktop
-            rm -rf /usr/share/applications/kde4/ubiquity-kdeui.desktop
-            rm -rf /usr/share/applications/ubiquity.desktop
-            rm -rf /etc/rc.local
-            rm -r /etc/apt
-            tar -xf /root/apt.tar.gz -C /
-            rm -rf /root/apt.tar.gz
-            apt-get -y -q purge firefox-locale-en libreoffice-help-en-*
-            update-apt-xapian-index -vf
-            #Place your custom commands below this line
-            #Example to remove PinguyBuilder and clean up packages
-
-            #apt-get purge pinguybuilder --yes --assume-yes
-            #apt-get --yes --assume-yes autoremove
-
-            #Place your custom commands above this line
-            ES=\$?
-            [ "\$VERBOSE" != no ] && log_end_msg \$ES
-            return \$ES
-        fi
-
-
-
-
-}
-
-case "\$1" in
-    start)
-        do_start
-        ;;
-    restart|reload|force-reload)
-        echo "Error: argument '\$1' not supported" >&2
-        exit 3
-        ;;
-    stop)
-        ;;
-    *)
-        echo "Usage: \$0 start|stop" >&2
-        exit 3
-        ;;
-esac
-
-FOO
-
-fi
-
-
 # load the PinguyBuilder.conf file
 . /etc/PinguyBuilder.conf
 
@@ -170,6 +97,85 @@ deb http://archive.ubuntu.com/ubuntu bionic-security multiverse
 deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted
 deb http://archive.ubuntu.com/ubuntu bionic-updates universe
 deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse"
+fi
+
+if [ "$SUCCESSCOMMAND" = "" ]; then
+    SUCCESSCOMMAND=""
+fi
+
+if [ "$FIRSTBOOTCOMMANDS" = "" ]; then
+    FIRSTBOOTCOMMANDS=""
+fi
+
+#create PinguyBuilder-firstboot script if it doesn't exist and populate with at least removal of the ubiquity*.desktop file from users Desktop and fix for recovery mode
+fbtest=`grep "REM302" /etc/init.d/PinguyBuilder-firstboot`
+
+if [ "$fbtest" = "" ]; then
+    cat > /etc/init.d/PinguyBuilder-firstboot <<FOO
+#! /bin/sh
+### BEGIN INIT INFO
+# Provides:          PinguyBuilder-firstboot
+# Required-Start:    \$remote_fs \$syslog \$all
+# Required-Stop:
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: Run firstboot items for PinguyBuilder after a remastered system has been installed
+### END INIT INFO
+
+PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin:/usr/local/sbin
+
+. /lib/init/vars.sh
+. /lib/lsb/init-functions
+
+do_start() {
+        #REM302
+        if [ "\`cat /proc/cmdline | grep casper\`" = "" ]; then
+            [ "\$VERBOSE" != no ] && log_begin_msg "Running PinguyBuilder-firstboot"
+            (sleep 60 && update-rc.d -f PinguyBuilder-firstboot remove) &
+            sed -i -e 's/root:x:/root:!:/g' /etc/shadow
+            rm -rf /home/*/*/ubiquity*.desktop
+            rm -rf /usr/share/applications/kde4/ubiquity-kdeui.desktop
+            rm -rf /usr/share/applications/ubiquity.desktop
+            rm -rf /etc/rc.local
+            rm -r /etc/apt
+            tar -xf /root/apt.tar.gz -C /
+            rm -rf /root/apt.tar.gz
+            apt-get -y -q purge firefox-locale-en libreoffice-help-en-*
+            update-apt-xapian-index -vf
+            #Place your custom commands below this line
+            #Example to remove PinguyBuilder and clean up packages
+
+            #apt-get purge pinguybuilder --yes --assume-yes
+            #apt-get --yes --assume-yes autoremove
+
+            $FIRSTBOOTCOMMANDS
+
+            #Place your custom commands above this line
+            ES=\$?
+            [ "\$VERBOSE" != no ] && log_end_msg \$ES
+            return \$ES
+        fi
+
+}
+
+case "\$1" in
+    start)
+        do_start
+        ;;
+    restart|reload|force-reload)
+        echo "Error: argument '\$1' not supported" >&2
+        exit 3
+        ;;
+    stop)
+        ;;
+    *)
+        echo "Usage: \$0 start|stop" >&2
+        exit 3
+        ;;
+esac
+
+FOO
+
 fi
 
 case $1  in
@@ -548,6 +554,10 @@ log_msg "Renaming Distro to $LIVECDLABEL"
 
     #copy any preseed files
     cp /etc/PinguyBuilder/preseed/* $WORKDIR/ISOTMP/preseed/
+    cat > $WORKDIR/ISOTMP/preseed/configured_success_command.seed <<EOF
+ubiquity  ubiquity/success_command string \
+$SUCCESSCOMMAND
+EOF
 
     #BOOT Type is isolinux
     log_msg "Copying memtest86+ for the live system"
